# Generated by Django 4.2.4 on 2024-03-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetails',
            name='description',
        ),
    ]
